events {}

http {
    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Garante que os arquivos estáticos (CSS/JS) sejam servidos corretamente
        location /_static/ {
            alias /usr/share/nginx/html/_static/;
            autoindex on;
        }

        # Serve arquivos como CSS, JS, imagens e fontes
        location ~* \.(css|js|png|jpg|jpeg|gif|ico|woff|woff2|ttf|svg|eot|otf)$ {
            try_files $uri =404;
            access_log off;
            expires 30d;
        }

        gzip on;
        gzip_types text/plain text/css application/json application/javascript;
        gzip_min_length 1000;
    }
}
